version: "3.3"
services:
  mysql_db:
    image: mysql:8.0.16 #ghcr.io/linuxserver/mariadb
    container_name: mysql_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE # pragma: allowlist secret
      - secure-file-priv=""
      - TZ=America/Los_Angeles
      # - MYSQL_DATABASE=baseball
      - SQL_CLIENT_PORT=3307
    command: --performance-schema --secure-file-priv="" --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - "3307"
    hostname: mysql_db
    restart: unless-stopped
    networks:
      hw5-net:
        aliases:
          - mysql-db
  client:
    container_name: client
    depends_on: [mysql_db]
    build:
      context: .
      dockerfile: Dockerfile.hw5
    ports:
      - "8000:8000"
    # # If need to step in:
    # tty: true
    # stdin_open: true
    # entrypoint:
    #   - sh
    volumes:
      - ./results:/results
    networks:
      hw5-net:
        aliases:
          - hw5
networks:
  hw5-net:
